spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kodilla_course
    username: root
    password: Szefunio050687
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect