spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/kodilla_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: kodilla
    password: Asdjkl1290
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update